name: widgets
description: "A Flutter widgets project"

# ? version
version: 1.0.0+1

# ? environment
environment:
  sdk: ^3.7.0

# ? dependencies
dependencies:
  flutter:
    sdk: flutter

  # core
  hive_flutter: ^1.1.0
  get: ^4.7.2

  # extra
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

  # network
  dio: ^5.8.0+1
  internet_connection_checker: ^3.0.1
  signalr_core: ^1.1.2

  # ui
  cupertino_icons: ^1.0.8
  awesome_snackbar_content: ^0.1.5
  flutter_screenutil: ^5.9.3

# ? dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ? flutter
flutter:
  uses-material-design: true

  # ? assets
  assets:
    - assets/icons/
    - assets/images/

  # ? fints:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          # style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
