name: widgets
description: "A Flutter widgets project."

# ? version
version: 1.0.0+1

# ? environment
environment:
  sdk: ^3.7.0

# ? dependencies
dependencies:
  flutter:
    sdk: flutter

  # core
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  get: ^4.7.2

  # extra
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1

# ? dev_dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ? flutter
flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
